version: "3.5"
services:
  postsService:
    image: posts-image
    ports:
      - "4000:4000"
    networks:
      - blog

  commentsService:
    image: comments-image
    ports:
      - "4001:4001"
    networks:
      - blog

  queryService:
    image: query-image
    depends_on:
      - event-busService
    ports:
      - "4002:4002"
    networks:
      - blog

  moderationService:
    image: moderation-image
    ports:
      - "4003:4003"
    networks:
      - blog

  event-busService:
    image: event-bus-image
    ports:
      - "4005:4005"
    networks:
      - blog

networks:
  blog:
