apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      image: posts-image
      imagePullPolicy: Never
      ports:
        - containerPort: 4000
      env:
        - name: EVENT_BUS_URL
          value: "http://event-bus-service:4005/events"